<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'5L2c5ZOB5qyj6LWP');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[3]=array(0,6,1,'5pyN5Yqh5oql5Lu3');
$cfg_Cs[4]=array(0,2,1,'5a6i54mH5bGV56S6');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(1,2,1,'6Z+p5Zu95ama57qx5pGE5b2x');
$cfg_Cs[7]=array(1,2,1,'5aSW5pmv5ama57qx5pGE5b2x');
$cfg_Cs[8]=array(2,1,1,'5LyY5oOg5rS75Yqo');
$cfg_Cs[9]=array(2,1,1,'6KGM5Lia6LWE6K6v');
$cfg_Cs[10]=array(3,6,1,'6Z+p5Zu95ama57qx5pGE5b2x');
$cfg_Cs[11]=array(3,6,1,'5aSW5pmv5ama57qx5pGE5b2x');
?>