<dl>
                        <dt><img src="../templets/hssy/images/time.png" height="57" width="68" /><span class="span1"><h1>[field:pubdate function=MyDate('d',@me)/]</h1>[field:pubdate function=MyDate('Y/m',@me)/]</span></dt>
                        <dd class="dd1"><a>[field:textlink/]</a></dd>
                        <dd class="dd2"><a><i>POST TIME:[field:pubdate function=MyDate("Fj,Y",@me)/]</i></a></dd>
                        <dd class="dd3"><a>[field:description/]</a></dd>
                        <dd class="dd4"><a><span class="spa">已有<span class="sp2">[field:click/]</span>人阅读</span></a></dd>
                	</dl>