{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/hssy/uploads/allimg/151111/1-151111192A6.jpg' text='' width='2560' height='1920'} /hssy/uploads/allimg/151111/1-151111192A6.jpg {/dede:img}
{dede:img ddimg='/hssy/uploads/allimg/151111/1-151111193Q0.jpg' text='' width='444' height='530'} /hssy/uploads/allimg/151111/1-151111193Q0.jpg {/dede:img}
