<dl>
                        <dt><img src="../templets/hssy/images/time.png" height="57" width="68" /><span class="span1"><h1>07</h1>2012/06</span></dt>
                        <dd class="dd1"><a href="#">[field:textlink/]</a></dd>
                        <dd class="dd2"><a href="#"><i>POST TIME:[field:pubdate function=MyDate("Fj,Y",@me)/]</i></a></dd>
                        <dd class="dd3"><a href="#">[field:description/]</a></dd>
                        <dd class="dd4"><a href="news1.html"><span class="spa">已有<span class="sp2">506</span>人阅读</span><span class="sp1">查看详情</span></a></dd>
                	</dl>