<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /hssy/uploads/allimg/151112/1-1511120K514.jpg ",93,248);
$z[1][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120K514.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="500";
$z[1][4]['height']="382";
$z[2]=Array("img"," /hssy/uploads/allimg/151112/1-1511120K514-50.jpg ",250,411);
$z[2][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120K514-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="353";
$z[2][4]['height']="418";
$z[3]=Array("img"," /hssy/uploads/allimg/151112/1-1511120K514-51.jpg ",413,574);
$z[3][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120K514-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="354";
$z[3][4]['height']="395";
$z[4]=Array("img"," /hssy/uploads/allimg/151112/1-1511120K515.jpg ",576,731);
$z[4][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120K515.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="397";
$z[4][4]['height']="307";

?>