<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /hssy/uploads/allimg/151116/1-151116191J1.jpg ",93,248);
$z[1][4]['ddimg']="/hssy/uploads/allimg/151116/1-151116191J1.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="444";
$z[1][4]['height']="530";

?>