<?php
$z[0]=Array("pubdate","",127,168);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",173,216);
$z[1][4]['function']="MyDate('Y/m',@me)";
$z[2]=Array("textlink","",273,290);
$z[3]=Array("arcurl","",350,365);
$z[4]=Array("pubdate","",380,424);
$z[4][4]['function']="MyDate(\"Fj,Y\",@me)";
$z[5]=Array("arcurl","",488,503);
$z[6]=Array("description","",505,525);
$z[7]=Array("arcurl","",585,600);
$z[8]=Array("click","",644,658);

?>