<div class="product1">
                	
                	[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
                    <p><a href="[field:arcurl/]">[field:title/]<span>[field:trueprice/]&nbsp;</span>元</a></p>
                    <h4><a href="#">【套系亮点】</a></h4>
                </div>