<dl>
                        <dt><img src="{dede:global.cfg_templets_skin/}/templets/hssy/images/time.png" height="57" width="68" /><span class="span1"><h1>[field:pubdate function=MyDate('d',@me)/]</h1>[field:pubdate function=MyDate('Y/m',@me)/]</span></dt>
                        <dd class="dd1"><a>[field:textlink/]</a></dd>
                        
                        <dd class="dd3"><a><i>[field:description/]</i></a></dd>
                        
                	</dl>