<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /hssy/uploads/allimg/151112/1-1511120KH9.png ",93,246);
$z[1][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120KH9.png";
$z[1][4]['text']="";
$z[1][4]['width']="219";
$z[1][4]['height']="180";
$z[2]=Array("img"," /hssy/uploads/allimg/151112/1-1511120KH9-50.png ",248,407);
$z[2][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120KH9-50.png";
$z[2][4]['text']="";
$z[2][4]['width']="219";
$z[2][4]['height']="180";
$z[3]=Array("img"," /hssy/uploads/allimg/151112/1-1511120KI0.png ",409,562);
$z[3][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120KI0.png";
$z[3][4]['text']="";
$z[3][4]['width']="219";
$z[3][4]['height']="180";
$z[4]=Array("img"," /hssy/uploads/allimg/151112/1-1511120KI0-50.png ",564,723);
$z[4][4]['ddimg']="/hssy/uploads/allimg/151112/1-1511120KI0-50.png";
$z[4][4]['text']="";
$z[4][4]['width']="219";
$z[4][4]['height']="180";

?>