<dl class="mar">
				<dt>[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}'><img src='{@me['litpic']}'/></a>"); [/field:array]<p>01<span>HOT</span></p></dt>
					<dd class="dd"><a href="#">VIVI Service</a></dd>
					<dd class="dd1"><a href="[field:arcurl/]">[field:title/]</a></dd>
					<dd><a href="#"><span class="span">&nbsp;优惠价格:</span><span class="sp1">&yen;[field:trueprice/]</span></a></dd>
        		</dl>