<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",321,353);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",704,736);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",825,857);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1031,1063);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span class=\"letter\">[field:typename/]</span><span class=\"word1\">HOME</span></a></li>\r\n      	",1265,1461);
$z[5][4]['type']="top";
$z[5][4]['row']="10";

?>