<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",200,302);
$z[2]=Array("global","",356,388);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",947,969);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1004,1033);
$z[4][4]['name']="position";
$z[5]=Array("field","",1236,1257);
$z[5][4]['name']="content";
$z[6]=Array("include","",2059,2096);
$z[6][4]['filename']="footer.htm";

?>