<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",192,294);
$z[2]=Array("global","",328,360);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",919,941);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",976,1005);
$z[4][4]['name']="position";
$z[5]=Array("arclist","\r\n            <li>\r\n           <a  href=\"[field:arcurl/]\">[field:description/]</a>[field:pubdate function=MyDate('Y.m.d',@me)/]<br/>\r\n           </li>\r\n           ",1136,1369);
$z[5][4]['row']="10";
$z[5][4]['titlelen']="24";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("include","",1481,1518);
$z[6][4]['filename']="footer.htm";

?>