<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.html";
$z[1]=Array("global","",189,221);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channelartlist","\r\n			 			<li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n						",298,448);
$z[2][4]['typeid']="3";
$z[3]=Array("global","",545,577);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",669,701);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",783,815);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",980,1012);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1201,1233);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1422,1454);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1643,1675);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1970,2002);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",2075,2107);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",2752,2784);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("field","",2945,2967);
$z[13][4]['name']="typename";
$z[14]=Array("field","",2988,3017);
$z[14][4]['name']="position";
$z[15]=Array("arclist","  \r\n                <div class=\"product1\">	\r\n                	[field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}'><img src='{@me['litpic']}'/></a>\"); [/field:array]\r\n                    <p><a href=\"[field:arcurl/]\">[field:title/]<span>[field:trueprice/]&nbsp;</span>元</a></p>\r\n                    <h4><a>【套系亮点】</a></h4>\r\n                </div>     \r\n           ",3048,3525);
$z[15][4]['channelid']="6";
$z[15][4]['addfields']="trueprice";
$z[16]=Array("include","",3596,3634);
$z[16][4]['filename']="footer.html";

?>