<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",181,283);
$z[2]=Array("global","",317,349);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",897,919);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",951,980);
$z[4][4]['name']="position";
$z[5]=Array("field","",1062,1083);
$z[5][4]['name']="content";
$z[6]=Array("include","",1215,1252);
$z[6][4]['filename']="footer.htm";

?>