<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.html";
$z[1]=Array("global","",1604,1636);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1714,1746);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("arclist","\r\n	      <li>\r\n	      	 [field:imglink/]\r\n	      </li>\r\n       ",2755,2891);
$z[3][4]['typeid']="1";
$z[3][4]['imgwidth']="444";
$z[3][4]['imgheight']="530";
$z[4]=Array("include","",2944,2982);
$z[4][4]['filename']="footer.html";

?>