<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",171,203);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",762,784);
$z[2][4]['name']="typename";
$z[3]=Array("field","",819,848);
$z[3][4]['name']="position";
$z[4]=Array("field","",925,946);
$z[4][4]['name']="content";
$z[5]=Array("include","",1016,1053);
$z[5][4]['filename']="footer.htm";

?>