<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.html";
$z[1]=Array("global","",1143,1175);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1253,1285);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("arclist","\r\n\r\n		<li>[field:imglink/]</li>\r\n\r\n		",2304,2428);
$z[3][4]['typeid']="4";
$z[3][4]['imgwidth']="444";
$z[3][4]['imgheight']="530";
$z[3][4]['limit']="0,20";
$z[4]=Array("include","",2470,2508);
$z[4][4]['filename']="footer.html";

?>