<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",160,192);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",751,773);
$z[2][4]['name']="typename";
$z[3]=Array("field","",808,837);
$z[3][4]['name']="position";
$z[4]=Array("arclist","\r\n			<dl>\r\n                 <dt>[field:imglink/]</dt>\r\n                 <dd>[field:textlink/]</dd>\r\n            </dl> \r\n            ",941,1142);
$z[4][4]['titlelen']="24";
$z[4][4]['typeid']="4";
$z[4][4]['channelid']="2";
$z[5]=Array("include","",1298,1335);
$z[5][4]['filename']="footer.htm";

?>